### ISSUE TITLE
Non-standard Fiddler install folder?

### ISSUE THREAD

**Issue by rswafford** [gotdibbs/Imposter.Fiddler#11]
Hey Dibbs, how can I make the installer recognize a non-standard Fiddler install location? Is there a command line switch or something I can pass into the installer?

**Comment by gotdibbs** [comment]
Hey dude! The installer should be reading from your registry to determine the install location (see [here](https://github.com/gotdibbs/Imposter.Fiddler/blob/master/Imposter.Fiddler.Installer/MainWindow.xaml.cs#L49)).

That said, the installer is just copying everything from the adjacent `Scripts` folder from the installer zip over to the corresponding Fiddler folder, so you could also do it by hand.

**Comment by rswafford** [comment]
Perfect, just copied it over manually - that did the trick. Thanks!
