### ISSUE TITLE
MissingMethodException on every request

### ISSUE THREAD

**Issue by rajyraman** [gotdibbs/Imposter.Fiddler#5]
After installing the extension, I am getting this error for every request. Is there something that I have not done/configured?

```
Method not found: 'Fiddler.HTTPResponseHeaders Fiddler.Session.get_ResponseHeaders()'.

Type: System.MissingMethodException

Source: Imposter.Fiddler
   at Imposter.Fiddler.Imposter.AutoTamperRequestBefore(Session oSession)
   at Fiddler.FiddlerExtensions.DoAutoTamperRequestBefore(Session oSession)
   at Fiddler.Session._executeObtainRequest()
   at Fiddler.Session.InnerExecute()
   at Fiddler.Session.Execute(Object objThreadState)

Fiddler v4.4.9.2 (x64 AMD64) [.NET 4.0.30319.34209 on Microsoft Windows NT 6.1.7601 Service Pack 1] 
```

**Comment by gotdibbs** [comment]
Hi! Sorry to hear you're having issues.

Can you please try updating Fiddler? It looks like you're on `4.4.9.2`, I am currently on `4.6.2.32002` and am not experiencing this issue.

If that still doesn't work, I'll look into this a bit further.

**Comment by rajyraman** [comment]
Yup. I actually updated right after posting the issue and that fixed it :)

**Comment by gotdibbs** [comment]
![image](https://cloud.githubusercontent.com/assets/1540648/18456159/72274fd8-7914-11e6-977e-03f3c1d6f355.png)

Glad it's working now. Thanks for the update!
