### ISSUE TITLE
Install issue with new Fiddler install Location

### ISSUE THREAD

**Issue by pmalecka** [gotdibbs/Imposter.Fiddler#7]
Hi gotdibbs,

the new versions of Fiddler have their install location stored in HKCU, instead of HKLM.

This results in the installer not finding the install location.

It might help to try and look in HKCU as well - if the location is not found in HKLM.

Best,
Peter

**Comment by gotdibbs** [comment]
Thanks! I'm a bit swamped at the moment, so I likely can't get to this soon myself, but if you'd like to take a stab at it feel free to submit a PR!

**Comment by gotdibbs** [comment]
Looks like this is now in `HKCU\Software\Microsoft\Fiddler2\InstallerSettings` => `ScriptPath`. I'll get this updated as soon as I can unless someone gets to it before me.
