### ISSUE TITLE
Installer Error on Mac

### ISSUE THREAD

**Issue by zaynrahn** [gotdibbs/Imposter.Fiddler#8]
When I try to run the Install.exe file using the mono runtime command, the following error message comes up:
<img width="1089" alt="screen shot 2017-11-19 at 10 21 59 pm" src="https://user-images.githubusercontent.com/16835247/33001595-d8b1833c-cd7c-11e7-9fc5-c254c6f94a8d.png">

I have also tried using the non-32 bit mono runtime command as well. But still no luck. 
Is Imposter able to run on Mac or this functionality not yet available?

**Comment by gotdibbs** [comment]
@zaynrahn I do not have a mac, physical or VM, to test this on so no macOS support. This is intended to be Windows only.

That said, with a quick search I've determined that mono does not appear to support one of the core technologies this app is built on: WPF (see: http://www.mono-project.com/docs/gui/wpf/). If you'd like, you could presumably fork and rework the presentation layer to make Imposter's logic work on macOS ... though I don't even know if Fiddler works on macOS.

An alternative for you would be to use the rewrite tool in Charles (see: https://www.charlesproxy.com/documentation/tools/rewrite/). I have not personally used it, but it should work on the same basic principle.

Hope that helps!

**Comment by zaynrahn** [comment]
@gotdibbs Thank you for the prompt reply and the additional resources.
