### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by devkeydet** [gotdibbs/Imposter.Fiddler#9]
How do I uninstall this?

**Comment by devkeydet** [comment]
I looked at the source code.  You need to remove the following files from your scripts directory:
Imposter.Fiddler.dll
imposter.js
MahApps.Metro.dll
PropertyTools.dll
PropertyTools.Wpf.dll
System.Windows.Interactivity.dll

**Comment by gotdibbs** [comment]
@devkeydet Yep, you got it. All it does is copy those files. Thanks for posting an update!

If you have any feedback on why you're uninstalling, that'd be much appreciated too!

**Comment by devkeydet** [comment]
It messed up the dpi of fiddler and caused everything to be unusable.  I am on a Surface Book with high resolution.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gotdibbs** [comment]
@devkeydet That's weird. We run external monitors off of surfaces here with varying DPIs between the two and I've never heard of an issue like that coming across. I'll open a separate issue to investigate further.

**Comment by gotdibbs** [comment]
@devkeydet I spent a bit of time on this and it appears that Fiddler doesn't run in DPI aware mode by default. Launching fiddler with the switch `-dpiAware` as noted [here](https://textslashplain.com/2015/10/16/whats-new-in-fiddler-4-6-0-7/) seems to fix the issue.

I caught up on their future plans and it looks like Orchestra/WebUI is their next goal, and that the percentage of users like us with high DPI devices is low, so this likely will not be resolved (without the use of the switch) in the WinForms incarnation of Fiddler anytime soon (if at all).
